pin qgis to an older version
latest version breaks sqlite in the python installation:
```
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/conda/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /opt/conda/lib/python3.11/lib-dynload/_sqlite3.cpython-311-aarch64-linux-gnu.so: undefined symbol: sqlite3_deserialize
```

This prevents jupyter from starting up